apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: productivity

resources:
  - linkerd-policy.yaml
  - externalsecret.yaml
  - pvc.yaml
  - serviceaccount.yaml
  - vpa.yaml

commonLabels:
  app.kubernetes.io/name: nextcloud
  app.kubernetes.io/managed-by: argocd
