apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-env
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homepage-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/productivity/homepage-env
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-qbit-env
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homepage-qbit-env
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_QBIT_USERNAME
      remoteRef:
        key: apps/media/qb-webui-creds
        property: username
    - secretKey: HOMEPAGE_VAR_QBIT_PASSWORD
      remoteRef:
        key: apps/media/qb-webui-creds
        property: password
    - secretKey: HOMEPAGE_VAR_QBIT_LTS_USERNAME
      remoteRef:
        key: apps/media/qb-lts-webui-creds
        property: username
    - secretKey: HOMEPAGE_VAR_QBIT_LTS_PASSWORD
      remoteRef:
        key: apps/media/qb-lts-webui-creds
        property: password
    - secretKey: HOMEPAGE_VAR_QBIT_LTS2_USERNAME
      remoteRef:
        key: apps/media/qb-lts2-webui-creds
        property: username
    - secretKey: HOMEPAGE_VAR_QBIT_LTS2_PASSWORD
      remoteRef:
        key: apps/media/qb-lts2-webui-creds
        property: password
