apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: productivity

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - externalsecret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - vpa.yaml

configMapGenerator:
  - name: homepage-assets
    files:
      - background.webp=assets/dashboard-background.webp
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"

commonLabels:
  app.kubernetes.io/name: homepage
  app.kubernetes.io/managed-by: argocd
