apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-gateway
imagePullSecrets:
  - name: harbor-pull-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-static-a
imagePullSecrets:
  - name: harbor-pull-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-static-b
imagePullSecrets:
  - name: harbor-pull-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-swap
imagePullSecrets:
  - name: harbor-pull-creds
