apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whiteboard-jwt
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: whiteboard-jwt
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: apps/productivity/nextcloud-identity
        property: whiteboard-jwt-secret
