apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: productivity

resources:
  - externalsecret.yaml
  - networkpolicy.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - vpa.yaml

labels:
  - pairs:
      app.kubernetes.io/name: whiteboard
      app.kubernetes.io/managed-by: argocd
    includeSelectors: true
