apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upstream/rbac-snapshot-controller.yaml
  - upstream/setup-snapshot-controller.yaml
  - upstream/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  - upstream/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  - upstream/snapshot.storage.k8s.io_volumesnapshots.yaml

patches:
  - path: deployment-patch.yaml
