apiVersion: v1
kind: ServiceAccount
metadata:
  name: librechat
imagePullSecrets:
  - name: harbor-pull-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: librechat-rag-api
imagePullSecrets:
  - name: harbor-pull-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: librechat-meilisearch
imagePullSecrets:
  - name: harbor-pull-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: librechat-mongodb
imagePullSecrets:
  - name: harbor-pull-creds
