apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-config
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: authentik-config
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: apps/identity/authentik
        property: secret-key
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: apps/identity/authentik
        property: postgresql-password
    - secretKey: AUTHENTIK_EMAIL__USERNAME
      remoteRef:
        key: apps/identity/authentik
        property: smtp-username
    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: apps/identity/authentik
        property: smtp-password
    - secretKey: AUTHENTIK_OIDC_IMMICH_CLIENT_SECRET
      remoteRef:
        key: apps/identity/authentik
        property: oidc-immich-client-secret
    - secretKey: AUTHENTIK_OIDC_NEXTCLOUD_CLIENT_SECRET
      remoteRef:
        key: apps/identity/authentik
        property: oidc-nextcloud-client-secret
    - secretKey: AUTHENTIK_OIDC_HEADSCALE_CLIENT_SECRET
      remoteRef:
        key: apps/identity/authentik
        property: oidc-headscale-client-secret
    - secretKey: AUTHENTIK_OIDC_LIBRECHAT_CLIENT_SECRET
      remoteRef:
        key: apps/identity/authentik
        property: oidc-librechat-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-pull-creds
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: harbor-pull-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: apps/productivity/harbor-pull-creds
        property: .dockerconfigjson
