apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - serviceaccount.yaml
  - externalsecret.yaml
  - blueprints-configmap.yaml
  - admin-ingress.yaml
  - networkpolicy.yaml
  - smtp-egress-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: identity-platform
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
