apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: identity-default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authentik-allowed-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: authentik
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-haproxy
      ports:
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 9443
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9300
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authentik-allowed-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: authentik
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: databases
          podSelector:
            matchLabels:
              cnpg.io/cluster: pg-platform
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: service-mesh
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8086
        - protocol: TCP
          port: 8090
