{
 "title": "Homepage Node / Melchior",
 "tags": [
  "homepage",
  "node"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node-exporter\", instance=\"192.168.1.13:9100\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=\"192.168.1.13:9100\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Network usage enp196s0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_network_receive_bytes_total{instance=\"192.168.1.13:9100\",device=\"enp196s0\"}[1m])",
     "legendFormat": "RX"
    },
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{instance=\"192.168.1.13:9100\",device=\"enp196s0\"}[1m])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Network usage enp197s0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_network_receive_bytes_total{instance=\"192.168.1.13:9100\",device=\"enp197s0\"}[1m])",
     "legendFormat": "RX"
    },
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{instance=\"192.168.1.13:9100\",device=\"enp197s0\"}[1m])",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}
{
 "title": "Homepage Node / Balthasar",
 "tags": [
  "homepage",
  "node"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node-exporter\", instance=\"192.168.1.14:9100\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=\"192.168.1.14:9100\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Network usage enp196s0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_network_receive_bytes_total{instance=\"192.168.1.14:9100\",device=\"enp196s0\"}[1m])",
     "legendFormat": "RX"
    },
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{instance=\"192.168.1.14:9100\",device=\"enp196s0\"}[1m])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Network usage enp197s0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_network_receive_bytes_total{instance=\"192.168.1.14:9100\",device=\"enp197s0\"}[1m])",
     "legendFormat": "RX"
    },
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{instance=\"192.168.1.14:9100\",device=\"enp197s0\"}[1m])",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}
{
 "title": "Homepage Node / Casper",
 "tags": [
  "homepage",
  "node"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node-exporter\", instance=\"192.168.1.15:9100\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=\"192.168.1.15:9100\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Network usage enp196s0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_network_receive_bytes_total{instance=\"192.168.1.15:9100\",device=\"enp196s0\"}[1m])",
     "legendFormat": "RX"
    },
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{instance=\"192.168.1.15:9100\",device=\"enp196s0\"}[1m])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Network usage enp197s0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_network_receive_bytes_total{instance=\"192.168.1.15:9100\",device=\"enp197s0\"}[1m])",
     "legendFormat": "RX"
    },
    {
     "expr": "8 * rate(node_network_transmit_bytes_total{instance=\"192.168.1.15:9100\",device=\"enp197s0\"}[1m])",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}