apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system-shared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/rrumana/k8s-homelab-2.git
    targetRevision: main
    path: cluster/platform/base/kube-system/shared
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
