apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ceph-block
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ceph-block-critical
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ceph-block-db
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 2
    requireSafeReplicaSize: true
