apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

resources:
  - ceph-cluster.yaml
  - ceph-block-pool.yaml
  - ceph-filesystem.yaml
  - ceph-nfs-bulk.yaml
  - ceph-nfs-bulk-export-job.yaml
  - ceph-nfs-bulk-service.yaml
  - rook-config-override.yaml
  - storage-class.yaml
  - storage-class-ceph-block-app-replicated.yaml
  - storage-class-ceph-block-critical.yaml
  - storage-class-ceph-block-db.yaml
  - storage-class-ceph-filesystem.yaml
  - storage-class-cephfs-replicated.yaml
  - storage-class-cephfs-bulk.yaml
  - volume-snapshot-class.yaml
  - toolbox.yaml
