apiVersion: batch/v1
kind: Job
metadata:
  name: rook-ceph-purge-osd-11-final
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app: rook-ceph-purge-osd
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: rook-ceph-purge-osd
    spec:
      restartPolicy: Never
      serviceAccountName: rook-ceph-purge-osd
      containers:
        - name: osd-removal
          image: harbor.rcrumana.xyz/mirror/rook/ceph:v1.19.3
          args:
            - ceph
            - osd
            - remove
            - --preserve-pvc
            - "false"
            - --force-osd-removal
            - "false"
            - --osd-ids
            - "11"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ROOK_MON_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: rook-ceph-mon-endpoints
                  key: data
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-username
            - name: ROOK_CONFIG_DIR
              value: /var/lib/rook
            - name: ROOK_CEPH_CONFIG_OVERRIDE
              value: /etc/rook/config/override.conf
            - name: ROOK_FSID
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: fsid
            - name: ROOK_LOG_LEVEL
              value: DEBUG
          volumeMounts:
            - name: ceph-conf-emptydir
              mountPath: /etc/ceph
            - name: rook-config
              mountPath: /var/lib/rook
            - name: ceph-admin-secret
              mountPath: /var/lib/rook-ceph-mon
      volumes:
        - name: ceph-admin-secret
          secret:
            secretName: rook-ceph-mon
            optional: false
            items:
              - key: ceph-secret
                path: secret.keyring
        - name: ceph-conf-emptydir
          emptyDir: {}
        - name: rook-config
          emptyDir: {}
