apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-rcrumana-xyz
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  secretName: harbor-rcrumana-xyz-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - harbor.rcrumana.xyz
