apiVersion: v1
kind: Service
metadata:
  name: authentik-embedded-outpost
  namespace: productivity
spec:
  type: ExternalName
  externalName: authentik-server.identity.svc.cluster.local
  ports:
    - name: http
      port: 80
      targetPort: 80
