apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-client
  namespace: productivity
  labels:
    security.rcrumana.xyz/exposure: private
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    haproxy-ingress.github.io/affinity: "cookie"
    haproxy-ingress.github.io/backend-protocol: "http"
    haproxy-ingress.github.io/auth-url: "svc://productivity/authentik-forward-auth:80/outpost.goauthentik.io/auth/nginx"
    haproxy-ingress.github.io/auth-signin: "https://dashboard.rcrumana.xyz/outpost.goauthentik.io/start?rd=%[url]"
    haproxy-ingress.github.io/auth-method: "GET"
    haproxy-ingress.github.io/auth-headers-request: "cookie,x-forwarded-host,x-forwarded-proto,x-original-url,x-original-method,user-agent,accept"
    haproxy-ingress.github.io/auth-headers-succeed: "x-authentik-username,x-authentik-groups,x-authentik-entitlements,x-authentik-email,x-authentik-name,x-authentik-uid,x-authentik-meta-app,x-authentik-meta-provider,x-authentik-meta-outpost,x-authentik-meta-version"
    haproxy-ingress.github.io/session-cookie-domain: "dashboard.rcrumana.xyz"
    haproxy-ingress.github.io/session-cookie-name: "homepage-client"
    haproxy-ingress.github.io/ssl-redirect: "true"
    haproxy-ingress.github.io/allowlist-source-range: "192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,100.64.0.0/10"
    haproxy-ingress.github.io/config-backend-early: |
      http-request set-header X-Forwarded-Host %[req.hdr(host)]
      http-request set-header X-Forwarded-Proto https
      http-request set-header X-Original-Method %[method]
      http-request set-header X-Original-URL https://%[req.hdr(host)]%[url]
    haproxy-ingress.github.io/config-backend: |
      http-response set-header X-Robots-Tag "noindex, nofollow"
spec:
  ingressClassName: haproxy-restricted
  tls:
    - hosts:
        - dashboard.rcrumana.xyz
      secretName: dashboard-rcrumana-xyz-tls
  rules:
    - host: dashboard.rcrumana.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage-client
                port:
                  number: 80
