apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: media
  labels:
    security.rcrumana.xyz/exposure: public
    security.rcrumana.xyz/public-approved: "true"
    security.rcrumana.xyz/public-edge: direct
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    haproxy-ingress.github.io/backend-protocol: "http"
    haproxy-ingress.github.io/timeout-client: "600s"
    haproxy-ingress.github.io/timeout-server: "600s"
    haproxy-ingress.github.io/proxy-body-size: "0"
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - immich.rcrumana.xyz
      secretName: immich-rcrumana-xyz-tls
  rules:
    - host: immich.rcrumana.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  number: 2283
