apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-app-replicated-config
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    app.kubernetes.io/component: server-migration
    app.kubernetes.io/managed-by: argocd
    vault.rcrumana.xyz/generation: app-replicated
data:
  extraconfig-from-values.hcl: |-
    ui = true
    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable = 1
    }
    storage "raft" {
      path = "/vault/data"
    }
    service_registration "kubernetes" {}

    disable_mlock = true
