apiVersion: v1
kind: Service
metadata:
  name: vault-app-replicated-internal
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    app.kubernetes.io/component: server-migration
    app.kubernetes.io/managed-by: argocd
    vault.rcrumana.xyz/generation: app-replicated
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: 8200
    - name: https-internal
      port: 8201
      protocol: TCP
      targetPort: 8201
  selector:
    app.kubernetes.io/name: vault
    vault.rcrumana.xyz/generation: app-replicated
