apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - externalsecret.yaml

commonLabels:
  app.kubernetes.io/part-of: metallb-system-shared
  app.kubernetes.io/managed-by: argocd
