apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-object-store
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: volsync-object-store
    creationPolicy: Owner
  data:
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: apps/platform/volsync-object-store
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: apps/platform/volsync-object-store
        property: RESTIC_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: apps/platform/volsync-object-store
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: apps/platform/volsync-object-store
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-queue-node-0-backup-restic
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: valkey-queue-node-0-backup-restic
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .resticRepository }}/valkey-queue-node-0-backup"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .awsAccessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .awsSecretAccessKey }}"
  data:
    - secretKey: resticRepository
      remoteRef:
        key: apps/platform/volsync-object-store
        property: RESTIC_REPOSITORY
    - secretKey: resticPassword
      remoteRef:
        key: apps/platform/volsync-object-store
        property: RESTIC_PASSWORD
    - secretKey: awsAccessKeyId
      remoteRef:
        key: apps/platform/volsync-object-store
        property: AWS_ACCESS_KEY_ID
    - secretKey: awsSecretAccessKey
      remoteRef:
        key: apps/platform/volsync-object-store
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-queue-node-1-backup-restic
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: valkey-queue-node-1-backup-restic
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .resticRepository }}/valkey-queue-node-1-backup"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .awsAccessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .awsSecretAccessKey }}"
  data:
    - secretKey: resticRepository
      remoteRef:
        key: apps/platform/volsync-object-store
        property: RESTIC_REPOSITORY
    - secretKey: resticPassword
      remoteRef:
        key: apps/platform/volsync-object-store
        property: RESTIC_PASSWORD
    - secretKey: awsAccessKeyId
      remoteRef:
        key: apps/platform/volsync-object-store
        property: AWS_ACCESS_KEY_ID
    - secretKey: awsSecretAccessKey
      remoteRef:
        key: apps/platform/volsync-object-store
        property: AWS_SECRET_ACCESS_KEY
