$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: librechat-data-backup
  namespace: ai
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: librechat-mongodb-data-backup
  namespace: ai
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: librechat-meilisearch-data-backup
  namespace: ai
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: arr-stack-gluetun-backup
  namespace: media
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: arr-stack-jellyseerr-config-backup
  namespace: media
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: arr-stack-lidarr-config-backup
  namespace: media
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: arr-stack-prowlarr-config-backup
  namespace: media
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: arr-stack-qbit-config-backup
  namespace: media
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: arr-stack-radarr-config-backup
  namespace: media
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: arr-stack-sonarr-config-backup
  namespace: media
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyfin-config-backup
  namespace: media
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: plex-config-backup
  namespace: media
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: headscale-data-backup
  namespace: other
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: elasticsearch-data-backup
  namespace: productivity
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nextcloud-appdata-backup
  namespace: productivity
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: uptime-kuma-data-backup
  namespace: productivity
---
$patch: delete
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden-data-backup
  namespace: productivity
