apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ci

resources:
  - externalsecrets.yaml
  - serviceaccount.yaml
  - metrics.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: gitea-actions
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
