apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-server-persistent-critical
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  storageClassName: ceph-block-critical
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-server-var-log-critical
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  storageClassName: ceph-block-critical
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-server-data-critical
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  storageClassName: ceph-block-critical
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-server-srv-critical
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  storageClassName: ceph-block-critical
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-server-var-lib-unifi-critical
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  storageClassName: ceph-block-critical
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-server-var-lib-mongodb-critical
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  storageClassName: ceph-block-critical
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-server-rabbitmq-ssl-critical
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  storageClassName: ceph-block-critical
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
