apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: search

resources:
  - opensearch-logs-cluster.yaml
  - data-prepper-configmap.yaml
  - data-prepper-deployment.yaml
  - data-prepper-service.yaml
  - fluent-bit-clusterrole.yaml
  - fluent-bit-clusterrolebinding.yaml
  - fluent-bit-configmap.yaml
  - fluent-bit-daemonset.yaml
  - fluent-bit-service.yaml
  - opensearch-ism-interval-v1-configmap.yaml
  - opensearch-ism-accelerate-v2-job.yaml
  - opensearch-retention-stage1-configmap.yaml
  - opensearch-retention-stage1-job.yaml
  - opensearch-retention-stage2-armed-configmap.yaml
  - opensearch-retention-stage2-armed-v2-job.yaml

commonLabels:
  app.kubernetes.io/part-of: observability-logging
  app.kubernetes.io/managed-by: argocd
