apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: foldingathome
  namespace: other
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: foldingathome
    creationPolicy: Owner
  data:
    - secretKey: ACCOUNT_TOKEN
      remoteRef:
        key: apps/other/foldingathome
        property: ACCOUNT_TOKEN
