apiVersion: v1
kind: Service
metadata:
  name: foldingathome
  labels:
    app: foldingathome
spec:
  clusterIP: None
  selector:
    app: foldingathome
  ports:
    - name: web
      port: 7396
      targetPort: web
