apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-client-env
  namespace: productivity
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homepage-client-env
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_JELLYFIN_API_KEY
      remoteRef:
        key: apps/productivity/homepage-env
        property: HOMEPAGE_VAR_JELLYFIN_API_KEY
    - secretKey: HOMEPAGE_VAR_JELLYSEERR_API_KEY
      remoteRef:
        key: apps/productivity/homepage-env
        property: HOMEPAGE_VAR_JELLYSEERR_API_KEY
    - secretKey: HOMEPAGE_VAR_IMMICH_API_KEY
      remoteRef:
        key: apps/productivity/homepage-env
        property: HOMEPAGE_VAR_IMMICH_API_KEY
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: apps/productivity/homepage-env
        property: HOMEPAGE_VAR_SONARR_API_KEY
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: apps/productivity/homepage-env
        property: HOMEPAGE_VAR_RADARR_API_KEY
    - secretKey: HOMEPAGE_VAR_LIDARR_API_KEY
      remoteRef:
        key: apps/productivity/homepage-env
        property: HOMEPAGE_VAR_LIDARR_API_KEY
