apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - externalsecret.yaml
  - media-library-bulk-final-delta-job.yaml
  - media-library-bulk-pvc.yaml
  - media-library-pv.yaml
  - media-library-torrent-eva-1-pv.yaml
  - media-library-torrent-eva-2-pv.yaml
  - media-library-torrent-eva-3-pv.yaml
  - media-library-torrent-eva-3-canary-pv.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/part-of: media-shared
  app.kubernetes.io/managed-by: argocd
