apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-bulk
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/name: media-library
    app.kubernetes.io/component: bulk-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7Ti
  storageClassName: cephfs-bulk-retain
  volumeMode: Filesystem
