apiVersion: v1
kind: ServiceAccount
metadata:
  name: immich-server
imagePullSecrets:
  - name: harbor-pull-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: immich-machine-learning
imagePullSecrets:
  - name: harbor-pull-creds
